/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#3b0900',
        'on-surface': '#1a1c1c',
        'error': '#ba1a1a',
        'inverse-on-surface': '#f1f1f1',
        'outline-variant': '#d0c6ab',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'surface-container-highest': '#e2e2e2',
        'on-secondary-fixed': '#2c0050',
        'inverse-surface': '#2f3131',
        'tertiary-fixed': '#ffdbd1',
        'inverse-primary': '#e9c400',
        'secondary-fixed-dim': '#ddb7ff',
        'primary-fixed': '#ffe16d',
        'surface-container-low': '#f3f3f3',
        'on-secondary-container': '#54118a',
        'on-primary-container': '#705e00',
        'surface-tint': '#705d00',
        'surface-dim': '#dadada',
        'surface': '#f9f9f9',
        'secondary-fixed': '#f0dbff',
        'primary-container': '#ffd700',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#221b00',
        'secondary-container': '#c588fe',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#b22e00',
        'error-container': '#ffdad6',
        'on-surface-variant': '#4d4732',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f9f9f9',
        'surface-container-high': '#e8e8e8',
        'on-primary-fixed-variant': '#544600',
        'tertiary-container': '#ffcfc2',
        'on-secondary-fixed-variant': '#622599',
        'primary-fixed-dim': '#e9c400',
        'tertiary-fixed-dim': '#ffb5a0',
        'primary': '#705d00',
        'on-background': '#1a1c1c',
        'surface-variant': '#e2e2e2',
        'surface-container': '#eeeeee',
        'on-primary': '#ffffff',
        'background': '#f9f9f9',
        'secondary': '#7b41b3',
        'tertiary': '#b12d00',
        'on-tertiary-fixed-variant': '#872000',
        'outline': '#7e775f',
      },
      fontFamily: {
        epilogue: ['Epilogue', 'sans-serif'],
        'work-sans': ['Work Sans', 'sans-serif'],
        'h1': ['Epilogue', 'sans-serif'],
        'h2': ['Epilogue', 'sans-serif'],
        'h3': ['Epilogue', 'sans-serif'],
        'price-display': ['Epilogue', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'body-lg': ['Work Sans', 'sans-serif'],
        'label-bold': ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        'h1': ['40px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'h2': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'h3': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'price-display': ['22px', { lineHeight: '1', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.2', fontWeight: '600' }],
      },
      spacing: {
        'xs': '4px',
        'base': '8px',
        'sm': '12px',
        'md': '24px',
        'lg': '40px',
        'xl': '64px',
        'gutter': '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
      borderRadius: {
        'xl': '16px',
      },
      boxShadow: {
        'custom': '0 4px 20px rgba(46, 16, 101, 0.04)',
        'card': '0 4px 20px rgba(46, 16, 101, 0.04)',
        'bottom-nav': '0 -4px 20px rgba(46, 16, 101, 0.06)',
        'cart-bar': '0 -8px 30px rgba(46, 16, 101, 0.1)',
      },
    },
  },
  plugins: [],
};
